// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qwlihyxmbhshvzpocfri.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InF3bGloeXhtYmhzaHZ6cG9jZnJpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU3ODEwMjgsImV4cCI6MjA3MTM1NzAyOH0.MvA1r9OGCdfhDCw22ZhkQ4n9dNr6BPicWMvnwdVrMM8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});