import { StyleSheet } from 'react-native';

// Professional Color System
const COLORS = {
  primary: '#10b981',
  secondary: '#3b82f6',
  accent: '#8b5cf6',
  danger: '#ef4444',
  warning: '#f59e0b',
  info: '#06b6d4',
  // Backgrounds
  bgPrimary: '#0f172a',
  bgSecondary: '#1e293b',
  bgTertiary: '#334155',
  // Text
  textPrimary: '#f1f5f9',
  textSecondary: '#cbd5e1',
  textTertiary: '#64748b',
  // Chart colors
  chartColors: ['#10b981', '#3b82f6', '#f59e0b', '#ef4444', '#8b5cf6', '#06b6d4'],
};

// Spacing System
const SPACING = {
  xs: 4,
  sm: 8,
  md: 12,
  lg: 16,
  xl: 20,
  xxl: 24,
};

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: COLORS.bgPrimary,
  },
  scrollView: {
    flex: 1,
  },
  header: {
    padding: SPACING.lg,
    borderBottomWidth: 1,
    borderBottomColor: COLORS.bgSecondary,
    backgroundColor: COLORS.bgSecondary,
  },
  headerTop: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    marginBottom: SPACING.sm,
  },
  headerTitle: {
    fontSize: 28,
    fontWeight: '900',
    color: COLORS.textPrimary,
    letterSpacing: -0.5,
  },
  headerSubtitle: {
    fontSize: 14,
    color: COLORS.textSecondary,
    marginTop: SPACING.xs,
    fontWeight: '500',
  },
  lastUpdate: {
    fontSize: 12,
    color: COLORS.textTertiary,
    fontWeight: '500',
  },
  liveBadge: {
    backgroundColor: COLORS.primary,
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 20,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    shadowColor: COLORS.primary,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.4,
    shadowRadius: 4,
    elevation: 4,
  },
  liveDot: {
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: '#fff',
  },
  liveText: {
    color: '#fff',
    fontSize: 11,
    fontWeight: '800',
    letterSpacing: 1,
  },
  statsGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'space-between',
    marginHorizontal: SPACING.lg,
    marginVertical: SPACING.md,
  },
  statCard: {
    backgroundColor: COLORS.bgSecondary,
    width: '31%',
    alignItems: 'center',
    borderRadius: 16,
    padding: SPACING.lg,
    marginBottom: SPACING.md,
    borderWidth: 1,
    borderColor: COLORS.bgTertiary,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    elevation: 5,
  },
  statValue: {
    fontSize: 20,
    fontWeight: '800',
    color: COLORS.primary,
    marginTop: SPACING.xs,
  },
  statLabel: {
    color: COLORS.textSecondary,
    fontWeight: '600',
    fontSize: 11,
    marginTop: SPACING.xs,
    textAlign: 'center',
  },
  section: {
    backgroundColor: COLORS.bgSecondary,
    marginHorizontal: SPACING.lg,
    marginBottom: SPACING.lg,
    borderRadius: 16,
    padding: SPACING.lg,
    borderWidth: 1,
    borderColor: COLORS.bgTertiary,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.25,
    shadowRadius: 4,
    elevation: 3,
  },
  sectionHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: SPACING.md,
  },
  sectionTitle: {
    fontSize: 20,
    fontWeight: '800',
    color: COLORS.textPrimary,
    letterSpacing: -0.3,
  },
  chartControls: {
    flexDirection: 'row',
    gap: SPACING.sm,
  },
  chartTypeButton: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    padding: SPACING.md,
    borderRadius: 12,
    borderWidth: 2,
    borderColor: COLORS.primary,
    gap: SPACING.sm,
    backgroundColor: 'transparent',
  },
  chartTypeButtonActive: {
    backgroundColor: COLORS.primary,
    shadowColor: COLORS.primary,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.4,
    shadowRadius: 4,
    elevation: 4,
  },
  chartTypeLabel: {
    color: COLORS.primary,
    fontWeight: '700',
    fontSize: 13,
  },
  chartTypeLabelActive: {
    color: '#fff',
  },
  chartSubtitle: {
    fontSize: 13,
    color: COLORS.textSecondary,
    marginBottom: SPACING.md,
    fontWeight: '500',
  },
  chartContainer: {
    justifyContent: 'center',
    alignItems: 'center',
    marginVertical: SPACING.sm,
  },
  chart: {
    borderRadius: 16,
    marginVertical: SPACING.sm,
  },
  emptyState: {
    alignItems: 'center',
    padding: SPACING.xxl * 2,
  },
  emptyIcon: {
    marginBottom: SPACING.lg,
    opacity: 0.5,
  },
  emptyTitle: {
    fontSize: 18,
    fontWeight: '700',
    color: COLORS.textPrimary,
    marginBottom: SPACING.sm,
    textAlign: 'center',
  },
  emptySubtitle: {
    fontSize: 14,
    color: COLORS.textSecondary,
    textAlign: 'center',
    lineHeight: 20,
  },
  legend: {
    marginTop: SPACING.lg,
    paddingTop: SPACING.lg,
    borderTopWidth: 1,
    borderTopColor: COLORS.bgTertiary,
  },
  legendItem: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: SPACING.sm,
    marginBottom: SPACING.sm,
    padding: SPACING.sm,
    borderRadius: 8,
  },
  legendDot: {
    width: 14,
    height: 14,
    borderRadius: 7,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.3,
    shadowRadius: 2,
    elevation: 2,
  },
  legendText: {
    color: COLORS.textSecondary,
    fontSize: 13,
    fontWeight: '500',
    flex: 1,
  },
  deviceDetailsList: {
    marginTop: SPACING.lg,
    gap: SPACING.sm,
  },
  deviceDetailItem: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: SPACING.md,
    backgroundColor: COLORS.bgTertiary,
    borderRadius: 12,
  },
  deviceDetailLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: SPACING.md,
    flex: 1,
  },
  deviceDetailRank: {
    fontSize: 16,
    fontWeight: '800',
    color: COLORS.primary,
    width: 28,
  },
  deviceDetailName: {
    color: COLORS.textPrimary,
    fontSize: 14,
    fontWeight: '700',
  },
  deviceDetailRoom: {
    color: COLORS.textTertiary,
    fontSize: 12,
    marginTop: 2,
    fontWeight: '500',
  },
  deviceDetailPower: {
    color: COLORS.primary,
    fontSize: 16,
    fontWeight: '800',
  },
  deviceCountBadge: {
    backgroundColor: COLORS.primary,
    paddingHorizontal: 12,
    paddingVertical: 4,
    borderRadius: 12,
  },
  deviceCountText: {
    color: '#fff',
    fontSize: 12,
    fontWeight: '800',
  },
  deviceListItem: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: SPACING.md,
    backgroundColor: COLORS.bgTertiary,
    borderRadius: 12,
    marginBottom: SPACING.sm,
  },
  deviceListLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: SPACING.md,
    flex: 1,
  },
  deviceStatusIndicator: {
    width: 10,
    height: 10,
    borderRadius: 5,
  },
  deviceListName: {
    color: COLORS.textPrimary,
    fontSize: 15,
    fontWeight: '700',
  },
  deviceListMeta: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    marginTop: 4,
  },
  deviceListInfo: {
    color: COLORS.textTertiary,
    fontSize: 12,
    fontWeight: '500',
  },
  deviceListDivider: {
    color: COLORS.textTertiary,
    fontSize: 12,
  },
  deviceListPower: {
    color: COLORS.primary,
    fontSize: 16,
    fontWeight: '800',
  },
  deviceListPowerOff: {
    color: COLORS.textTertiary,
  },
  actionButtons: {
    marginHorizontal: SPACING.lg,
    gap: SPACING.md,
  },
  simulatorButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: COLORS.accent,
    padding: SPACING.lg,
    borderRadius: 16,
    gap: SPACING.md,
    shadowColor: COLORS.accent,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.4,
    shadowRadius: 8,
    elevation: 5,
  },
  simulatorButtonText: {
    color: '#fff',
    fontSize: 17,
    fontWeight: '800',
  },
  betaBadge: {
    backgroundColor: 'rgba(255,255,255,0.2)',
    paddingHorizontal: 8,
    paddingVertical: 2,
    borderRadius: 8,
  },
  betaText: {
    color: '#fff',
    fontSize: 10,
    fontWeight: '800',
  },
  refreshButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: COLORS.primary,
    padding: SPACING.lg,
    borderRadius: 16,
    gap: SPACING.md,
    shadowColor: COLORS.primary,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.4,
    shadowRadius: 8,
    elevation: 5,
  },
  refreshButtonText: {
    color: '#fff',
    fontSize: 17,
    fontWeight: '800',
  },
  modalContainer: {
    flex: 1,
    backgroundColor: COLORS.bgPrimary,
  },
  modalHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: SPACING.lg,
    borderBottomWidth: 1,
    borderBottomColor: COLORS.bgSecondary,
    backgroundColor: COLORS.bgSecondary,
  },
  modalHeaderButton: {
    padding: SPACING.sm,
  },
  modalTitle: {
    fontSize: 20,
    fontWeight: '800',
    color: COLORS.textPrimary,
    letterSpacing: -0.3,
  },
  modalSummary: {
    flexDirection: 'row',
    justifyContent: 'space-around',
    padding: SPACING.xl,
    backgroundColor: COLORS.bgSecondary,
    marginHorizontal: SPACING.lg,
    marginVertical: SPACING.lg,
    borderRadius: 16,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.25,
    shadowRadius: 4,
    elevation: 3,
  },
  summaryItem: {
    alignItems: 'center',
    gap: SPACING.xs,
  },
  summaryValue: {
    fontSize: 22,
    fontWeight: '800',
    color: COLORS.primary,
  },
  summaryLabel: {
    fontSize: 12,
    color: COLORS.textSecondary,
    fontWeight: '600',
  },
  roomModalItem: {
    backgroundColor: COLORS.bgSecondary,
    padding: SPACING.lg,
    borderRadius: 16,
    marginBottom: SPACING.lg,
    borderWidth: 1,
    borderColor: COLORS.bgTertiary,
  },
  roomHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: SPACING.sm,
  },
  roomHeaderLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: SPACING.md,
  },
  roomColorIndicator: {
    width: 16,
    height: 16,
    borderRadius: 8,
  },
  roomName: {
    fontSize: 20,
    fontWeight: '800',
    color: COLORS.textPrimary,
  },
  roomPower: {
    fontSize: 24,
    fontWeight: '900',
    color: COLORS.primary,
  },
  roomPercentage: {
    color: COLORS.textSecondary,
    fontSize: 14,
    marginBottom: SPACING.md,
    fontWeight: '500',
  },
  roomStats: {
    flexDirection: 'row',
    gap: SPACING.lg,
    marginBottom: SPACING.md,
    paddingVertical: SPACING.md,
    borderTopWidth: 1,
    borderBottomWidth: 1,
    borderColor: COLORS.bgTertiary,
  },
  roomStatItem: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: SPACING.xs,
  },
  roomStat: {
    color: COLORS.textSecondary,
    fontSize: 13,
    fontWeight: '600',
  },
  deviceListTitle: {
    color: COLORS.textPrimary,
    fontSize: 15,
    fontWeight: '700',
    marginTop: SPACING.md,
    marginBottom: SPACING.sm,
  },
  deviceItem: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: SPACING.md,
    backgroundColor: COLORS.bgTertiary,
    borderRadius: 12,
    marginBottom: SPACING.sm,
  },
  deviceItemLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: SPACING.md,
    flex: 1,
  },
  deviceName: {
    color: COLORS.textPrimary,
    fontSize: 14,
    fontWeight: '600',
  },
  devicePower: {
    color: COLORS.primary,
    fontSize: 14,
    fontWeight: '800',
  },
  devicePowerOff: {
    color: COLORS.textTertiary,
  },
});

export { COLORS, SPACING, styles };
