import { StyleSheet, Dimensions } from 'react-native';

const { width } = Dimensions.get('window');

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#0a0a0b',
  },
  centerContent: {
    justifyContent: 'center',
    alignItems: 'center',
  },
  loadingText: {
    marginTop: 16,
    fontSize: 16,
    color: '#a1a1aa',
  },
  heroHeader: {
    padding: 24,
    paddingTop: 16,
  },
  headerTop: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    marginBottom: 24,
  },
  greetingContainer: {
    flex: 1,
  },
  greeting: {
    fontSize: 16,
    color: '#a1a1aa',
    marginBottom: 4,
  },
  userName: {
    fontSize: 32,
    fontWeight: '800',
    color: '#ffffff',
  },
  mainUsageCard: {
    backgroundColor: '#18181b',
    borderRadius: 24,
    padding: 28,
    alignItems: 'center',
    borderWidth: 1,
    borderColor: '#27272a',
    shadowColor: '#10b981',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.1,
    shadowRadius: 12,
    elevation: 8,
  },
  powerIconTouchable: {
    alignItems: 'center',
    justifyContent: 'center',
  },
  currentUsageLabel: {
    fontSize: 14,
    color: '#a1a1aa',
    marginBottom: 8,
    marginTop: 20,
    textTransform: 'uppercase',
    letterSpacing: 1,
  },
  currentUsageValue: {
    fontSize: 56,
    fontWeight: '800',
    color: '#10b981',
    marginBottom: 4,
  },
  currentUsageUnit: {
    fontSize: 16,
    color: '#71717a',
    marginBottom: 24,
  },
  usageDivider: {
    width: '100%',
    height: 1,
    backgroundColor: '#27272a',
    marginBottom: 20,
  },
  usageFooter: {
    flexDirection: 'row',
    width: '100%',
  },
  usageFooterItem: {
    flex: 1,
    alignItems: 'center',
  },
  usageFooterDivider: {
    width: 1,
    height: '100%',
    backgroundColor: '#27272a',
  },
  usageFooterValue: {
    fontSize: 18,
    fontWeight: '700',
    color: '#ffffff',
    marginBottom: 4,
  },
  usageFooterLabel: {
    fontSize: 12,
    color: '#a1a1aa',
  },
  quickActions: {
    flexDirection: 'row',
    paddingHorizontal: 24,
    gap: 12,
    marginBottom: 32,
  },
  actionButton: {
    flex: 1,
    alignItems: 'center',
  },
  actionIconContainer: {
    width: 56,
    height: 56,
    borderRadius: 16,
    backgroundColor: '#18181b',
    borderWidth: 1,
    borderColor: '#27272a',
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 8,
  },
  actionText: {
    fontSize: 12,
    color: '#a1a1aa',
    fontWeight: '600',
  },
  roomFilterSection: {
    marginBottom: 24,
  },
  sectionTitle: {
    fontSize: 20,
    fontWeight: '700',
    color: '#ffffff',
    paddingHorizontal: 24,
    marginBottom: 16,
  },
  roomFilter: {
    paddingHorizontal: 24,
  },
  roomFilterContent: {
    paddingRight: 24,
  },
  roomChip: {
    paddingHorizontal: 20,
    paddingVertical: 10,
    borderRadius: 20,
    marginRight: 10,
    backgroundColor: '#18181b',
    borderWidth: 1,
    borderColor: '#27272a',
  },
  roomChipActive: {
    backgroundColor: '#10b981',
    borderColor: '#10b981',
  },
  roomChipText: {
    fontSize: 14,
    fontWeight: '600',
    color: '#a1a1aa',
  },
  roomChipTextActive: {
    color: '#ffffff',
  },
  devicesSection: {
    paddingHorizontal: 24,
    marginBottom: 24,
  },
  devicesSectionHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 16,
  },
  deviceCount: {
    fontSize: 14,
    color: '#71717a',
    fontWeight: '600',
  },
  devicesGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 12,
  },
  deviceGridCard: {
    width: (width - 60) / 2,
    backgroundColor: '#18181b',
    borderRadius: 16,
    padding: 16,
    borderWidth: 1,
    borderColor: '#27272a',
  },
  deviceGridCardActive: {
    borderColor: '#10b981',
    backgroundColor: 'rgba(16, 185, 129, 0.05)',
  },
  deviceCardHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    marginBottom: 12,
  },
  deviceIconCircle: {
    width: 48,
    height: 48,
    borderRadius: 24,
    backgroundColor: '#27272a',
    justifyContent: 'center',
    alignItems: 'center',
  },
  deviceIconCircleActive: {
    backgroundColor: 'rgba(16, 185, 129, 0.2)',
  },
  statusIndicator: {
    width: 12,
    height: 12,
    borderRadius: 6,
    backgroundColor: '#3f3f46',
  },
  statusIndicatorActive: {
    backgroundColor: '#10b981',
  },
  deviceGridName: {
    fontSize: 16,
    fontWeight: '700',
    color: '#ffffff',
    marginBottom: 4,
  },
  deviceGridRoom: {
    fontSize: 12,
    color: '#71717a',
    marginBottom: 12,
  },
  deviceGridFooter: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  deviceGridUsage: {
    fontSize: 13,
    fontWeight: '600',
    color: '#a1a1aa',
  },
  deviceGridUsageActive: {
    color: '#10b981',
  },
  deviceGridStatus: {
    fontSize: 11,
    fontWeight: '700',
    color: '#52525b',
    textTransform: 'uppercase',
    letterSpacing: 0.5,
  },
  deviceGridStatusActive: {
    color: '#10b981',
  },
  emptyState: {
    alignItems: 'center',
    padding: 48,
    backgroundColor: '#18181b',
    borderRadius: 20,
    borderWidth: 1,
    borderColor: '#27272a',
    borderStyle: 'dashed',
  },
  emptyIconContainer: {
    width: 80,
    height: 80,
    borderRadius: 40,
    backgroundColor: 'rgba(16, 185, 129, 0.1)',
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 20,
  },
  emptyTitle: {
    fontSize: 20,
    fontWeight: '700',
    color: '#ffffff',
    marginBottom: 8,
    textAlign: 'center',
  },
  emptySubtitle: {
    fontSize: 14,
    color: '#a1a1aa',
    marginBottom: 28,
    textAlign: 'center',
    lineHeight: 20,
    paddingHorizontal: 20,
  },
  emptyActionButton: {
    backgroundColor: '#10b981',
    paddingVertical: 14,
    paddingHorizontal: 28,
    borderRadius: 12,
  },
  emptyActionText: {
    color: '#ffffff',
    fontSize: 15,
    fontWeight: '700',
  },
  tipSection: {
    marginHorizontal: 24,
    marginBottom: 24,
    padding: 20,
    backgroundColor: 'rgba(16, 185, 129, 0.08)',
    borderWidth: 1,
    borderColor: 'rgba(16, 185, 129, 0.3)',
    borderRadius: 16,
  },
  tipHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 12,
  },
  tipTitle: {
    fontSize: 16,
    fontWeight: '700',
    color: '#10b981',
    marginLeft: 12,
  },
  tipContent: {
    fontSize: 14,
    color: '#86efac',
    lineHeight: 20,
  },
  bottomSpacer: {
    height: 20,
  },
  // Modal Styles
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.85)',
    justifyContent: 'center',
    alignItems: 'center',
    padding: 24,
  },
  modalContainer: {
    width: '100%',
    maxWidth: 400,
    backgroundColor: '#18181b',
    borderRadius: 24,
    padding: 24,
    borderWidth: 1,
    borderColor: '#27272a',
  },
  modalCloseButton: {
    position: 'absolute',
    top: 16,
    right: 16,
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: '#27272a',
    justifyContent: 'center',
    alignItems: 'center',
    zIndex: 10,
  },
  modalContent: {
    alignItems: 'center',
  },
  modalIconContainer: {
    width: 80,
    height: 80,
    borderRadius: 40,
    backgroundColor: 'rgba(139, 92, 246, 0.15)',
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 20,
  },
  modalTitle: {
    fontSize: 24,
    fontWeight: '800',
    color: '#ffffff',
    marginBottom: 12,
    textAlign: 'center',
  },
  modalDescription: {
    fontSize: 15,
    color: '#a1a1aa',
    textAlign: 'center',
    lineHeight: 22,
    marginBottom: 24,
    paddingHorizontal: 8,
  },
  modalPrimaryButton: {
    width: '100%',
    backgroundColor: '#10b981',
    paddingVertical: 16,
    borderRadius: 12,
    alignItems: 'center',
    marginBottom: 12,
  },
  modalPrimaryButtonText: {
    color: '#ffffff',
    fontSize: 16,
    fontWeight: '700',
  },
  modalSecondaryButton: {
    width: '100%',
    backgroundColor: '#27272a',
    paddingVertical: 16,
    borderRadius: 12,
    alignItems: 'center',
  },
  modalSecondaryButtonText: {
    color: '#a1a1aa',
    fontSize: 16,
    fontWeight: '600',
  },
  modalFeatureList: {
    width: '100%',
    marginBottom: 20,
  },
  modalFeatureItem: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 12,
    paddingHorizontal: 16,
  },
  modalFeatureBullet: {
    color: '#10b981',
    fontSize: 20,
    marginRight: 12,
    fontWeight: '700',
  },
  modalFeatureText: {
    color: '#d4d4d8',
    fontSize: 15,
    flex: 1,
  },
  modalComingSoonBadge: {
    backgroundColor: 'rgba(245, 158, 11, 0.15)',
    paddingHorizontal: 16,
    paddingVertical: 8,
    borderRadius: 20,
    marginBottom: 24,
    borderWidth: 1,
    borderColor: 'rgba(245, 158, 11, 0.3)',
  },
  modalComingSoonText: {
    color: '#f59e0b',
    fontSize: 13,
    fontWeight: '700',
    textTransform: 'uppercase',
    letterSpacing: 1,
  },
  modalCurrentStats: {
    width: '100%',
    backgroundColor: '#27272a',
    padding: 20,
    borderRadius: 16,
    alignItems: 'center',
    marginBottom: 24,
    borderWidth: 1,
    borderColor: '#3f3f46',
  },
  modalCurrentLabel: {
    fontSize: 13,
    color: '#a1a1aa',
    marginBottom: 8,
    textTransform: 'uppercase',
    letterSpacing: 1,
  },
  modalCurrentValue: {
    fontSize: 32,
    fontWeight: '800',
    color: '#10b981',
  },
  modalSubtitle: {
    fontSize: 16,
    fontWeight: '600',
    color: '#ffffff',
    marginBottom: 16,
    alignSelf: 'flex-start',
  },
  modalGoalOption: {
    width: '100%',
    backgroundColor: '#27272a',
    padding: 16,
    borderRadius: 12,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 12,
    borderWidth: 1,
    borderColor: '#3f3f46',
  },
  modalGoalOptionContent: {
    flex: 1,
  },
  modalGoalOptionTitle: {
    fontSize: 16,
    fontWeight: '700',
    color: '#ffffff',
    marginBottom: 4,
  },
  modalGoalOptionTarget: {
    fontSize: 13,
    color: '#10b981',
  },
  modalGoalSetStats: {
    width: '100%',
    flexDirection: 'row',
    backgroundColor: '#27272a',
    borderRadius: 16,
    padding: 20,
    marginBottom: 24,
    borderWidth: 1,
    borderColor: '#3f3f46',
  },
  modalGoalSetItem: {
    flex: 1,
    alignItems: 'center',
  },
  modalGoalSetDivider: {
    width: 1,
    backgroundColor: '#3f3f46',
    marginHorizontal: 16,
  },
  modalGoalSetLabel: {
    fontSize: 12,
    color: '#a1a1aa',
    marginBottom: 8,
    textTransform: 'uppercase',
    letterSpacing: 1,
  },
  modalGoalSetValue: {
    fontSize: 24,
    fontWeight: '800',
    color: '#ffffff',
    marginBottom: 4,
  },
  modalGoalSetSub: {
    fontSize: 11,
    color: '#71717a',
  },
});

export default styles;
